name: BlackMoon Krnln

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bmkrnln-debug-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # Add msuild to local environment
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1

    # Test build
    - name: Build BlackMoon Krnln
      run: msbuild Project/krnln_VS2019.vcxproj /p:configuration=debug /p:platform=win32 -maxcpucount:4
  
  bmkrnln-release-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # Add msuild to local environment
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      
    # Test build
    - name: Build BlackMoon Krnln
      run: msbuild Project/krnln_VS2019.vcxproj /p:configuration=release /p:platform=win32 -maxcpucount:4
